AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bastion host for SSH tunneling to VPC resources (OpenSearch, etc.)'

Parameters:
  VpcId:
    Type: String
    Default: vpc-06340a61
    Description: VPC ID for deployment (same as main stack)

  SubnetId:
    Type: String
    Default: subnet-f36b6ea8
    Description: Public subnet ID for bastion host

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 key pair for SSH access

  AllowedSSHCidr:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR block allowed to SSH (recommend restricting to your IP, e.g., 1.2.3.4/32)

  InstanceType:
    Type: String
    Default: t4g.nano
    Description: EC2 instance type (t4g.nano is cheapest at ~$3/month)
    AllowedValues:
      - t4g.nano
      - t4g.micro
      - t3.micro
      - t3.nano

  # Use SSM Parameter Store to get latest Amazon Linux 2023 AMI
  LatestAmiArm64:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64

  LatestAmiX86:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Conditions:
  IsARM: !Or
    - !Equals [!Ref InstanceType, t4g.nano]
    - !Equals [!Ref InstanceType, t4g.micro]

Resources:
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for bastion host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedSSHCidr
          Description: SSH access
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-bastion-sg

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !If
        - IsARM
        - !Ref LatestAmiArm64
        - !Ref LatestAmiX86
      KeyName: !Ref KeyPairName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-bastion

  BastionEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref BastionInstance
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-bastion-eip

Outputs:
  BastionPublicIP:
    Description: Public IP address of the bastion host
    Value: !Ref BastionEIP
    Export:
      Name: !Sub ${AWS::StackName}-public-ip

  SSHCommand:
    Description: SSH command to connect to bastion
    Value: !Sub 'ssh -i ~/.ssh/${KeyPairName}.pem ec2-user@${BastionEIP}'

  OpenSearchTunnelCommand:
    Description: SSH tunnel command for OpenSearch (replace OPENSEARCH_ENDPOINT)
    Value: !Sub 'ssh -i ~/.ssh/${KeyPairName}.pem -L 9243:OPENSEARCH_ENDPOINT:443 -N ec2-user@${BastionEIP}'
