AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront and S3 static site hosting for static-site application'

Parameters:
  DomainName:
    Type: String
    Default: static-site.com
    Description: Domain name for the application

  HostedZoneId:
    Type: String
    Default: ZXXXXXXXXXXXXX
    Description: Existing Route53 Hosted Zone ID

  CloudFrontCertificateArn:
    Type: String
    Description: ARN of the ACM certificate for CloudFront (must be in us-east-1)

Resources:
  #############################################
  # S3 Bucket for Static Assets
  #############################################

  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-assets
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - !Sub 'https://www.${DomainName}'
              - !Sub 'https://${DomainName}'
            MaxAge: 3600
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-assets

  # Origin Access Control for CloudFront to access S3
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AWS::StackName}-oac
        Description: OAC for assets bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Bucket policy allowing CloudFront access via OAC
  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${AssetsBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  #############################################
  # CloudFront Distribution
  #############################################

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CloudFront for ${DomainName} - S3 static site'
        Aliases:
          - !Ref DomainName
          - !Sub 'www.${DomainName}'
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2and3
        PriceClass: PriceClass_100
        DefaultRootObject: index.html

        # Origins
        Origins:
          # S3 Origin for static assets
          - Id: S3Origin
            DomainName: !GetAtt AssetsBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ''

        # Default behavior - S3 for static assets
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          # CachingOptimized policy for static assets
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          # CORS-S3Origin policy
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf

        # SPA fallback - serve index.html for 403/404 errors
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0

      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-distribution

  #############################################
  # Route 53 Records
  #############################################

  # Route53 A Record for apex domain (points to CloudFront)
  ApexCloudFrontRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        # CloudFront hosted zone ID is always Z2FDTNDATAQYW2
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  # Route53 A Record for www subdomain (points to CloudFront)
  WwwCloudFrontRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'www.${DomainName}'
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        # CloudFront hosted zone ID is always Z2FDTNDATAQYW2
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  AssetsBucketName:
    Description: Name of the S3 bucket for assets
    Value: !Ref AssetsBucket

  AssetsBucketArn:
    Description: ARN of the S3 bucket for assets
    Value: !GetAtt AssetsBucket.Arn

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution

  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontURL:
    Description: CloudFront URL
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'

  DomainURL:
    Description: Application URL with domain
    Value: !Sub 'https://${DomainName}'
