AWSTemplateFormatVersion: '2010-09-09'
Description: 'ACM Certificate for static-site application'

##############################################
# This template creates an ACM certificate with DNS validation.
# Run ./create-cert.sh to create cert in us-east-1 for CloudFront.
##############################################

Parameters:
  DomainName:
    Type: String
    Default: static-site.com
    Description: Domain name for the application

  HostedZoneId:
    Type: String
    Default: ZXXXXXXXXXXXXX
    Description: Existing Route53 Hosted Zone ID

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub '*.${DomainName}'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-cert

Outputs:
  CertificateArn:
    Description: ARN of the ACM certificate
    Value: !Ref Certificate
    Export:
      Name: !Sub ${AWS::StackName}-CertificateArn
